__all__ = ['pdb2xyz', 'pdb2lammpsdata', 'lammpstrj2lammpsdata', 'npy2poscar', 'poscar2xyz', 'xyz2npy', 
           'xyz2lammpstrj', 'lammpstrj2xyz', 'xsd2pdb']



from ...check import check_module, check_func


def pdb2xyz(dir_init="", dir_target="", names=['O', 'H']):
    '''
    通用函数，用于将pdb格式文件转换为xyz格式文件。

    参数：
        dir_init - 初始目录路径
        dir_target - 目标目录路径

    返回：
        返回记录值
    '''
    mda = check_module('MDAnalysis')
    os = check_module('os')

    u = mda.Universe(os.path.join(dir_init, 'system.pdb'))
    atoms = u.select_atoms("name " + names[0])
    for name in names[1:]:
        atoms += u.select_atoms("name "+name)

    with open(os.path.join(dir_target, "system.xyz"), 'w') as file_xyz:
        file_xyz.write("%d\nframe 0\n" % atoms.n_atoms)
        for atom in atoms:
            file_xyz.write(atom.name + '\t%14.8f\t%14.8f\t%14.8f\n' 
                   % (atom.position[0], atom.position[1], atom.position[2]))

    print("The XYZ file has been generated at %s" % os.path.join(dir_target, "system.xyz"))

def pdb2lammpsdata(dir_init="", dir_target=""):
    '''
    通用函数，用于将pdb格式文件转换为lammpsdata格式文件。

    参数：
        dir_init - 初始目录路径
        dir_target - 目标目录路径

    返回：
        返回记录值
    '''
    mda = check_module('MDAnalysis')
    os = check_module('os')

    u = mda.Universe(os.path.join(dir_init, 'system.pdb'))

    for index, name in enumerate(names):
        atoms = u.select_atoms("name " + name)
        atoms.types = str(index + 1)
    atoms = u.select_atoms('all')

    with open(os.path.join(dir_target, "system.data"), 'w') as data:
        data.write("LAMMPS data file. dpmdlmp style. atom_style atomic generated by Arch.pdb2lammpsdata\n %d atoms\n" % atoms.n_atoms + 
                   " %d atom types\n" % len(names))
        data.write(" %.8f %.8f  xlo xhi\n" % (0.0, u.dimensions[0]) + 
                   " %.8f %.8f  ylo yhi\n" % (0.0, u.dimensions[1]) +
                   " %.8f %.8f  zlo zhi\n" % (0.0, u.dimensions[2]) +
                   " %.2f %.2f %.2f  xy xz yz\n\n" % (0, 0, 0))
        data.write(" Atoms # atomic\n\n")
        for index, atom in enumerate(atoms):
            data.write("%d\t%d\t" % (index+1, int(atom.type)) +
                       "%14.8f\t%14.8f\t%14.8f\n" % (atom.position[0], atom.position[1], atom.position[2]))

    print("The LAMMPSdata file has been generated at %s" % os.path.join(dir_target, "system.data"))

def lammpstrj2lammpsdata(dir_init="", dir_target=""):
    '''
    通用函数，用于将lammpstrj格式文件转换为lammpsdata格式文件。

    参数：
        dir_init - 初始目录路径
        dir_target - 目标目录路径

    返回：
        返回记录值
    '''
    mda = check_module('MDAnalysis')
    os = check_module('os')

    u = mda.Universe(os.path.join(dir_init, 'traj.lammpstrj'), format='LAMMPSDUMP')
    atoms = u.select_atoms('all')
    with open(os.path.join(dir_target, "system.data"), 'w') as data:
        data.write("LAMMPS data file. dpmdlmp style. atom_style atomic generated by Arch.lammpstrj2lammpsdata\n %d atoms\n" % atoms.n_atoms + 
                   " %d atom types\n" % len(set(atoms.types)))
        data.write(" %.8f %.8f  xlo xhi\n" % (0.0, u.dimensions[0]) + 
                   " %.8f %.8f  ylo yhi\n" % (0.0, u.dimensions[1]) +
                   " %.8f %.8f  zlo zhi\n" % (0.0, u.dimensions[2]) +
                   " %.2f %.2f %.2f  xy xz yz\n\n" % (0, 0, 0))
        data.write(" Atoms # atomic\n\n")
        for index, atom in enumerate(atoms):
            data.write("%d\t%d\t" % (index+1, int(atom.type)) +
                       "%14.8f\t%14.8f\t%14.8f\n" % (atom.position[0], atom.position[1], atom.position[2]))

    print("The LAMMPSdata file has been generated at %s" % os.path.join(dir_target, "system.data"))


def npy2poscar(dir_init="", dir_target="", multi=False, record=0):
    '''
    通用函数，用于将npy格式文件转换为POSCAR格式文件。

    参数：
        dir_init - 初始目录路径
        dir_target - 目标目录路径

    返回：
        返回记录值
    '''
    os = check_module('os')
    dp = check_module('dpdata')

    dir_poscar = os.path.join(dir_target, 'VASP_poscar')
    try:
        if multi:
            frames = dp.LabeledSystem(file_name=dir_init, fmt='deepmd/npy')
            if not os.path.exists(dir_poscar):
                os.makedirs(dir_poscar)
        else:
            frames = dp.LabeledSystem(file_name=os.path.join(dir_init, 'dpnpy'), fmt='deepmd/npy')
            os.makedirs(dir_poscar)
    except FileExistsError as e:
        import sys  
        sys.exit(e)
    else:
        for index in range(len(frames)):
            frames[index].to("vasp/poscar", os.path.join(dir_poscar, str(index+record)+'.poscar'))
        record += len(frames)
        
        print("The POSCAR file has been generated at %s" % dir_poscar)
        return record


def poscar2xyz(dir_init="", dir_target=""):
    '''
    通用函数，用于将POSCAR格式文件转换为xyz格式文件。

    dir_init：初始目录路径
    dir_target：目标目录路径
    '''
    os = check_module('os')
    read = check_func('ase.io', 'read')
    write = check_func('ase.io', 'write')

    dir_poscar = os.path.join(dir_init, 'VASP_poscar')
    dir_xyz = os.path.join(dir_target, 'QE_xyz')
    list_filenames = os.listdir(dir_poscar)
    try:
        os.makedirs(dir_xyz)
    except FileExistsError as e:
        import sys 
        sys.exit(e)
    else:
        for filename in list_filenames:
            file_poscar = os.path.join(dir_poscar, filename)
            frame = read(file_poscar, format='vasp')
            # 将Atoms对象保存为Quantum ESPRESSO的坐标文件
            espresso_coord_file = os.path.join(dir_xyz, filename+'.xyz')  
            write(espresso_coord_file, frame, format='xyz')

        print("The XYZ file has been generated at %s" % dir_xyz)


def xyz2npy(dir_init="", dir_target="", multi=False, record=0):
    '''
    通用函数，用于将xyz格式文件转换为npy格式文件。

    dir_init：初始目录路径
    dir_target：目标目录路径
    '''
    os = check_module('os')
    dp = check_module('dpdata')

    dir_npy = os.path.join(dir_target, 'dpnpy')
    try:
        if multi:
            frames = dp.LabeledSystem(file_name=dir_init, fmt='qe/cp/traj')
            if not os.path.exists(dir_npy):
                os.makedirs(dir_npy)
            dir_npy_index = os.makedirs(os.path.join(dir_npy, str(record)))
            record += 1
            frames.to("deepmd/npy", dir_npy_index)
        else:
            frames = dp.LabeledSystem(file_name=os.path.join(dir_init, 'QE_pos', 'cp'), fmt='qe/cp/traj')
            os.makedirs(dir_npy)
            frames.to("deepmd/npy", dir_npy)
    except FileExistsError as e:
        import sys 
        sys.exit(e)
    else:
        print("The deepmd/npy file has been generated at %s" % dir_npy)

        return record

def xsd2pdb(dir_init="", dir_target="", filename="system.xsd"):
    '''
    通用函数，用于将xsd格式文件转换为pdb格式文件。

    dir_init：初始目录路径
    dir_target：目标目录路径
    '''
    os = check_module('os')
    read = check_func('ase.io', 'read')
    write = check_func('ase.io', 'write')

    file_xsd = os.path.join(dir_init, filename)
    file_pdb = os.path.join(dir_target, 'system.pdb')
    frame = read(file_xsd, format='xsd') 
    write(file_pdb, frame, format='proteindatabank')

    print("The PDB file has been generated at %s" % file_pdb)

def xyz2lammpstrj(dir_init="", dir_target=""):
    '''
    通用函数，用于将xyz格式文件转换为lammpstrj格式文件。

    dir_init：初始目录路径
    dir_target：目标目录路径
    '''
    os = check_module('os')
    dp = check_module('dpdata')

    dir_lammpstrj = os.path.join(dir_target, 'LAMMPS_lammpstrj')
    try:
        frames = dp.LabeledSystem(file_name=os.path.join(dir_init, 'QE_pos', 'cp'), fmt='qe/cp/traj')
        os.makedirs(dir_lammpstrj)
    except FileExistsError as e:
        import sys 
        sys.exit(e)
    else:
        with open(os.path.join(dir_lammpstrj, 'cp.lammpstrj'), 'w') as file_lammpstrj:
            num_atoms = sum(frames["atom_numbs"])
            for frame in frames:
                file_lammpstrj.write("ITEM: TIMESTEP\n" +
                                    "10\n" +
                                    "ITEM: NUMBER OF ATOMS\n" + 
                                    str(num_atoms) + "\n" +
                                    "ITEM: BOX BOUNDS pp pp pp\n")
                for i in range(3):
                    file_lammpstrj.write("%.14f %.14f\n" %(0.0, frame["cells"][0, i, i]))
                file_lammpstrj.write("ITEM: ATOMS id type x y z\n")
                for id_atoms in range(0, num_atoms):
                    file_lammpstrj.write("%d %d %.8f %.8f %.8f\n"
                        %(id_atoms+1, frame["atom_types"][id_atoms], 
                        frame["coords"][0, id_atoms, 0], 
                        frame["coords"][0, id_atoms, 1],
                        frame["coords"][0, id_atoms, 2]))

        print("The LAMMPStrj file has generated at %s" % dir_lammpstrj)

def lammpstrj2xyz(dir_init="", dir_target="", names=['O', 'H']):
    '''
    通用函数，用于将lammpstrj格式文件转换为xyz格式文件。

    dir_init：初始目录路径
    dir_target：目标目录路径
    '''
    mda = check_module('MDAnalysis')
    os = check_module('os')

    u = mda.Universe(os.path.join(dir_init, 'traj.lammpstrj'), format='LAMMPSDUMP')
    u.add_TopologyAttr('name')

    for index, name in enumerate(names):
        atoms = u.select_atoms("type " + str(index+1))
        atoms.names = name
    atoms = u.select_atoms("name " + names[0])

    for name in names[1:]:
        atoms += u.select_atoms("name "+name)
        for frame in u.trajectory[-1]:    
            with open(os.path.join(dir_target, 'relax.xyz'), 'w') as file_xyz:
                file_xyz.write(str(atoms.n_atoms)+"\n")
                file_xyz.write("frame 0\n")
                for atom in atoms:
                    file_xyz.write(atom.name + '\t%14.8f\t%14.8f\t%14.8f\n' 
                                % (atom.position[0], atom.position[1], atom.position[2]))

    print("The XYZ file has generated at %s" % dir_target)